# Project Information
site_name: Scarf Documentation
site_url: https://docs.scarf.sh/
site_description: |
  Scarf's Technical Documentation & API Reference
copyright: Copyright &copy; 2019 - 2026 Scarf Systems, Inc. <img referrerpolicy="no-referrer-when-downgrade" src="https://static.scarf.sh/a.png?x-pxid=c9065f3a-a090-4243-8f69-145d5de7bfca" />

# Repository
repo_name: scarf-sh/docs
repo_url: https://github.com/scarf-sh/docs

# Config
theme:
  name: material
  logo: assets/scarf-tm-logo-white.svg
  custom_dir: overrides
  palette:
    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode

    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
  font:
    text: Roboto
    code: Roboto Mono
  favicon: assets/icon.svg
  icon:
    logo: assets/new_scarf.svg

# Styles
extra_css:
  - "stylesheets/extra.css"

extra_javascript:
  - javascripts/vendor/mermaid.min.js
  - javascripts/mermaid.js

# Docs Navigation
nav:
- Overview: index.md
- Getting Started:
  - Getting Started Checklist: getting-started-checklist.md
  - Quick Start: quick-start.md
  - FAQ: faq.md
- Organizations and Billing:
  - Setting Up Your Organization: organizations.md
  - Scarf for Foundation-Backed Projects: foundation-backed-projects.md
  - Billing and Pricing: billing-and-pricing.md
- Setup and Data Collection:
  - Scarf Gateway: gateway.md
  - Setting Up Scarf Packages: packages.md
  - Package Registry Integrations:
    - Maven Central: package-registry-integrations-maven-central.md
  - Scarf SDKs for Library and Package Authors: package-analytics.md
  - Custom Telemetry: custom-telemetry.md
  - Scarf Pixels: web-traffic.md
  - Importing Events: event-import.md
- Insights and Company Data:
  - How Company Matching Works: company-matching.md
  - Intent Scoring: intent-scoring.md
  - Scarf AI: scarf-ai.md
  - Open Source Qualified Leads (OQLs): oql.md
  - Open Source Adoption Funnel Stages: funnel-stages.md
  - Making Sense of Your Scarf Insights: understanding-your-insights.md
- Sales and CRM:
  - Lead Generation - Scarf's Sales Prospecting Service: sales-prospecting.md
  - CRM Integrations:
    - Overview: crm-overview.md
    - Salesforce: salesforce.md
    - HubSpot: hubspot.md
- Data and Developer Tools:
  - Data Export: data-export.md
  - API Docs: https://api-docs.scarf.sh/v2.html
- Help and Updates:
  - User Guide and Best Practices: user_best_practices.md
  - Troubleshooting: troubleshooting.md
  - Changelog: changelog.md

# Analytics
google_analytics:
  - auto
  - G-GH3EXW7112

# Extensions
markdown_extensions:
  meta: {}
  admonition: {}
  pymdownx.superfences: {}
  tables: {}
  sane_lists: {}

# Customization
extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/scarf-sh
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/scarf_oss
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/company/scarf-sh
    - icon: fontawesome/brands/slack
      link: https://tinyurl.com/scarf-community-slack
    - icon: fontawesome/brands/youtube
      link: https://www.youtube.com/channel/UCiJRrlBKBOgYFRO9eb6pfdg

# Plugins
plugins:
  - render_swagger
  - search
